AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GarageDoorMonitorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
              - "iot.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: 'GarageDoorMonitorPolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "cloudwatch:PutMetricData"

  GarageDoorMonitorIoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: "Allow"
          Action:
            - "iot:Connect"
          Resource:
            # TODO put in the real placeholder
            - "arn:aws:iot:us-east-1:${accountId}:client/${client.id.from.input}"
        -
          Effect: "Allow"
          Action:
          - "iot:Publish"
          Resource:
          - "arn:aws:iot:us-east-1:123456789012:topic/${iot:Connection.Thing.ThingTypeName}/${iot:Connection.Thing.ThingName}"

  GarageDoorMonitorOpenRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Description: 'Garage door monitor reports magnetic reed switch is OPEN (magnetic field not present)'
        Sql: >-
          SELECT status FROM 'home/garage/garageDoorSensor' WHERE status = 0
        RuleDisabled: 'false'
        Actions:
          -
            CloudwatchMetric:
              MetricName: GarageDoorStatus
              MetricNamespace: Garage
              MetricUnit: None
              # this depends on how the sensor is actually installed
              MetricValue: '1'
              RoleArn:
                Fn::GetAtt:
                  - "GarageDoorMonitorRole"
                  - "Arn"
  GarageDoorMonitorCloseRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Description: 'Garage door monitor reports magnetic reed switch is CLOSE (magnetic field present)'
        Sql: >-
          SELECT status FROM 'home/garage/garageDoorSensor' WHERE status = 1
        RuleDisabled: 'false'
        Actions:
          -
            CloudwatchMetric:
              MetricName: GarageDoorStatus
              MetricNamespace: Garage
              MetricUnit: None
              # this depends on how the sensor is actually installed
              MetricValue: '0'
              RoleArn:
                Fn::GetAtt:
                - "GarageDoorMonitorRole"
                - "Arn"
  GarageDoorOpenedFor10MinsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmDescription: 'Garage door has been opened for 10 mins'
      MetricName: 'GarageDoorStatus'
      Namespace: 'Garage'
      Statistic: 'Average'
      Period: 60
      EvaluationPeriods: 10
      Threshold: 1.0
      ComparisonOperator: 'GreaterThanOrEqualToThreshold'
      TreatMissingData: 'missing'
Outputs:
  GarageDoorMonitorOpenRule:
    Description: 'Rule triggered when garage door monitor reports magnetic reed switch is OPEN'
    Value: !Ref GarageDoorMonitorOpenRule
  GarageDoorMonitorCloseRule:
    Description: 'Rule triggered when garage door monitor reports magnetic reed switch is CLOSE'
    Value: !Ref GarageDoorMonitorCloseRule